version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:${POSTGRESQL_VERSION:-14.8.0}'
    container_name: postgresql
    ports:
      - 45432:5432
    env_file:
      - .env
    volumes:
      - ${POSTGRESQL_0:-./data/postgresql_0}:/bitnami/postgresql
      - ./custom-conf/:/bitnami/postgresql/conf/conf.d/
    restart: always
    shm_size: 2gb
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=${POSTGRES_POSTGRES_PASSWD:-password}
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=${POSTGRES_ADMIN_PASSWD:-password}
      - POSTGRESQL_DATABASE=postgres
      - TZ=Asia/Shanghai